In [63]:
import pandas as pd
import pandas as pd
import ast
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [64]:
df = pd.read_csv('data.csv')

df_artist = pd.read_csv('data_w_genres.csv')
df_genre = pd.read_csv('data_by_genres.csv')
df_year = pd.read_csv('data_by_year.csv')
df_artists = pd.read_csv('data_by_artist.csv')

In [65]:

df_key = df[['key']]
df_key_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_key).toarray()

In [66]:
df.drop(['key'], axis=1, inplace=True)
key_indices = [f'key_{i}' for i in range(12)]
print(key_indices)

['key_0', 'key_1', 'key_2', 'key_3', 'key_4', 'key_5', 'key_6', 'key_7', 'key_8', 'key_9', 'key_10', 'key_11']

In [67]:
df = df.join(pd.DataFrame(df_key_onehot, columns=key_indices))

In [68]:
df.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,...,key_2,key_3,key_4,key_5,key_6,key_7,key_8,key_9,key_10,key_11
0,0gNNToCW3qjabgTyBSjt3H,!Que Vida! - Mono Version,['Love'],220560,11/1/66,1966,0.5250,0.600,0.540,0.00305,...,0,0,0,0,0,0,0,1,0,0
1,0tMgFpOrXZR6irEOLNWwJL,"""40""",['U2'],157840,2/28/83,1983,0.2280,0.368,0.480,0.70700,...,0,0,0,0,0,0,1,0,0,0
2,2ZywW3VyVx6rrlrX75n3JB,"""40"" - Live",['U2'],226200,8/20/83,1983,0.0998,0.272,0.684,0.01450,...,0,0,0,0,0,0,1,0,0,0
3,6DdWA7D1o5TU2kXWyCLcch,"""40"" - Remastered 2008",['U2'],157667,2/28/83,1983,0.1850,0.371,0.545,0.58200,...,0,0,0,0,0,0,1,0,0,0
4,3vMmwsAiLDCfyc1jl76lQE,"""40"" - Remastered 2008",['U2'],157667,2/28/83,1983,0.1850,0.371,0.545,0.58200,...,0,0,0,0,0,0,1,0,0,0

In [69]:
df_mode = df[['mode']]
df_mode_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_mode).toarray()

In [70]:
df.drop(['mode'], axis=1, inplace=True)
df = df.join(pd.DataFrame(df_mode_onehot, columns=['minor', 'major']))

In [71]:
df2 = df.copy()

In [72]:
df_artist_key = df_artist[['key']]
df_artist_key_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_artist_key).toarray()
df_artist.drop(['key'], axis=1, inplace=True)

In [73]:
len(df_artist_key_onehot)

32539

In [74]:
df_artist = df_artist.join(pd.DataFrame(df_artist_key_onehot, columns=key_indices))

In [75]:
df_artist_mode = df_artist[['mode']]
df_artist_mode_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_artist_mode).toarray()

In [76]:
df_artist.drop(['mode'], axis=1, inplace=True)
df_artist = df_artist.join(pd.DataFrame(df_artist_mode_onehot, columns=['minor', 'major']))

In [77]:
df_artist.head()

,artists,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,...,key_4,key_5,key_6,key_7,key_8,key_9,key_10,key_11,minor,major
0,"""Cats"" 1981 Original London Cast",0.598500,0.470100,267072.000000,0.376203,0.010261,0.283050,-14.434300,0.209150,114.128800,...,0,1,0,0,0,0,0,0,0,1
1,"""Cats"" 1983 Broadway Cast",0.862538,0.441731,287280.000000,0.406808,0.081158,0.315215,-10.690000,0.176212,103.044154,...,0,1,0,0,0,0,0,0,0,1
2,"""Fiddler On The Roof” Motion Picture Chorus",0.856571,0.348286,328920.000000,0.286571,0.024593,0.325786,-15.230714,0.118514,77.375857,...,0,0,0,0,0,0,0,0,0,1
3,"""Fiddler On The Roof” Motion Picture Orchestra",0.884926,0.425074,262890.962963,0.245770,0.073587,0.275481,-15.639370,0.123200,88.667630,...,0,0,0,0,0,0,0,0,0,1
4,"""Joseph And The Amazing Technicolor Dreamcoat""...",0.510714,0.467143,270436.142857,0.488286,0.009400,0.195000,-10.236714,0.098543,122.835857,...,0,1,0,0,0,0,0,0,0,1

In [78]:
df_artist[['genres']].describe()

       genres
count   32539
unique  10841
top        []
freq    13563

In [79]:
df_genre_key = df_genre[['key']]
df_genre_key_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_genre_key).toarray()
df_genre.drop(['key'], axis=1, inplace=True)
df_genre = df_genre.join(pd.DataFrame(df_genre_key_onehot, columns=key_indices))

In [80]:
df_genre.head()

,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,...,key_2,key_3,key_4,key_5,key_6,key_7,key_8,key_9,key_10,key_11
0,21st century classical,0.754600,0.284100,3.525932e+05,0.159580,0.484374,0.168580,-22.153400,0.062060,91.351000,...,0,0,1,0,0,0,0,0,0,0
1,432hz,0.485515,0.312000,1.047430e+06,0.391678,0.477250,0.265940,-18.131267,0.071717,118.900933,...,0,0,0,0,0,0,0,0,0,1
2,8-bit,0.028900,0.673000,1.334540e+05,0.950000,0.630000,0.069000,-7.899000,0.292000,192.816000,...,0,0,0,1,0,0,0,0,0,0
3,[],0.535793,0.546937,2.495312e+05,0.485430,0.278442,0.220970,-11.624754,0.101511,116.068980,...,0,0,0,0,0,1,0,0,0,0
4,a cappella,0.694276,0.516172,2.018391e+05,0.330533,0.036080,0.222983,-12.656547,0.083627,105.506031,...,0,0,0,0,0,1,0,0,0,0

In [81]:
df_artist = df_artist.join(df_genre.set_index('genres'), on='genres', rsuffix='_gr')

In [82]:
df['artists'] = df['artists'].apply(ast.literal_eval)
df = df.explode('artists')
df_artist = df_artist.set_index('artists')
df.tail(25)

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,...,key_4,key_5,key_6,key_7,key_8,key_9,key_10,key_11,minor,major
169884,5hcO4JPFMFgQ5edWGhhhaG,괴도 (Danger),TAEMIN,191453,8/19/14,2014,0.02950,0.732,0.743,0.000000,...,0,0,0,0,0,0,0,0,0,1
169885,3Al8ZAfFrZshzgTI6IPeF1,깊은 밤을 날아서,Lee Moon Sae,182867,3/10/87,1987,0.63700,0.649,0.685,0.000139,...,0,0,0,0,0,0,0,0,0,1
169886,2p5TdDBoY6eEvTQuzyurTV,너의 의미 The Meaning of Yoy,Sanullim,223293,7/20/84,1984,0.47000,0.572,0.125,0.066900,...,1,0,0,0,0,0,0,0,1,0
169887,4qzBepJAKtYu4T1GDtBZZc,"눈,코,입 (Eyes, Nose, Lips)",TAEYANG,229990,6/13/14,2014,0.73800,0.631,0.516,0.000000,...,0,0,0,0,0,0,0,0,0,1
169888,72HYwYmfl6Y8AzbJO0z6vB,니가 하면 If You Do,GOT7,210834,11/23/15,2015,0.05570,0.692,0.886,0.000000,...,0,0,0,0,1,0,0,0,0,1
169889,0GU5GuJQQEnnREO2FxnVPT,달라달라 (DALLA DALLA),ITZY,199874,2/12/19,2019,0.00116,0.790,0.853,0.000042,...,0,0,0,0,0,0,0,1,1,0
169890,4ER58qECydWokIsgqtysWu,딱 좋아(Just right),GOT7,222399,7/13/15,2015,0.23300,0.760,0.781,0.000000,...,0,0,0,0,0,0,0,1,1,0
169891,5HiSc2ZCGn8L3cH3qSwzBT,러시안 룰렛 Russian Roulette,Red Velvet,211244,9/7/16,2016,0.05500,0.726,0.903,0.000225,...,0,0,0,1,0,0,0,0,1,0
169892,4mwzUFtpBHJVyBs16YjjPN,몸매 Mommae (feat. Ugly Duck),Jay Park,204327,11/5/15,2015,0.21800,0.745,0.669,0.000000,...,0,0,0,0,0,1,0,0,1,0
169892,4mwzUFtpBHJVyBs16YjjPN,몸매 Mommae (feat. Ugly Duck),Ugly Duck,204327,11/5/15,2015,0.21800,0.745,0.669,0.000000,...,0,0,0,0,0,1,0,0,1,0
169893,6DVq2uRrYyQfChAlsTJ11g,비처럼 음악처럼,Kim Hyunshik,277580,12/1/86,1986,0.04960,0.430,0.338,0.000000,...,0,1,0,0,0,0,0,0,0,1
169894,7nKQ5WAcjnG48knyLuo8gO,빨간 맛 Red Flavor,Red Velvet,191139,7/9/17,2017,0.04090,0.709,0.917,0.000000,...,0,0,0,0,0,1,0,0,0,1
169895,1XwAV7ty94aIJgRXP7CETn,사랑이 지나가면,Lee Moon Sae,253240,3/10/87,1987,0.76700,0.308,0.286,0.000746,...,0,1,0,0,0,0,0,0,0,1
169896,5hHlmrSV6d9LFMsDA1lamE,소방차 Fire Truck,NCT 127,178565,7/10/16,2016,0.11600,0.724,0.976,0.000013,...,0,0,0,0,0,0,0,0,0,1
169897,5w18nowVMRZrC5Na9Vxoth,"쏘리 쏘리 Sorry, Sorry",SUPER JUNIOR,232333,3/11/09,2009,0.02260,0.706,0.972,0.000003,...,0,0,0,0,0,0,0,1,1,0
169898,1uRB9bYGCSvLSsF4e65UYj,아로하,Cool,265379,4/19/04,2004,0.51600,0.529,0.754,0.000000,...,0,0,0,0,0,0,0,0,0,1
169899,4pi0Elz7B7cLfw37J3bYm9,으르렁 Growl,EXO,207053,8/5/13,2013,0.14500,0.681,0.814,0.000000,...,0,0,0,0,0,0,0,1,1,0
169900,2ujA6F1cpk3m8lsPE5aKua,전야 前夜 The Eve,EXO,176026,7/18/17,2017,0.02230,0.636,0.702,0.000000,...,0,0,0,0,0,0,0,0,1,0
169901,5NSPsOGVNWYOMeeyZPF7HY,중독 Overdose,EXO-K,205612,8/6/14,2014,0.06150,0.498,0.917,0.000000,...,0,1,0,0,0,0,0,0,1,0
169902,4KiYPYpm4ultIp247ftPlI,텅 빈 마음 Empty Heart,LEE SEUNG HWAN,249893,10/15/89,1989,0.42900,0.547,0.304,0.000000,...,0,0,0,0,0,0,0,1,1,0
169903,42tFTth2jcF7iSo0RBjfJF,피카부 Peek-A-Boo,Red Velvet,189050,11/17/17,2017,0.08680,0.839,0.902,0.002570,...,0,0,0,0,0,0,0,0,1,0
169904,6XP9L7di5JnOc9WaeAW8oe,행복 (Happiness),Red Velvet,220987,8/1/14,2014,0.32300,0.727,0.871,0.000006,...,0,0,0,0,0,0,1,0,1,0
169905,3Gpdzw72aBVJSrm5J1leVK,"헤어지지 못하는 여자, 떠나가지 못하는 남자 Can't Breakup Girl, C...",Leessang,284627,10/6/09,2009,0.15000,0.523,0.841,0.000000,...,0,0,0,0,0,0,1,0,1,0
169905,3Gpdzw72aBVJSrm5J1leVK,"헤어지지 못하는 여자, 떠나가지 못하는 남자 Can't Breakup Girl, C...",Jung In,284627,10/6/09,2009,0.15000,0.523,0.841,0.000000,...,0,0,0,0,0,0,1,0,1,0
169906,2p5DfmIUTLH79elmaSCCR5,화려하지 않은 고백 Confession Is Not Flashy,LEE SEUNG HWAN,230733,9/1/93,1993,0.44800,0.741,0.380,0.000811,...,0,0,0,0,0,0,0,0,0,1

In [83]:
df = df.join(df_artist, on='artists', rsuffix='_ar')

In [84]:
df.columns

Index(['id', 'name', 'artists', 'duration_ms', 'release_date', 'year',
       'acousticness', 'danceability', 'energy', 'instrumentalness',
       'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity',
       'explicit', 'key_0', 'key_1', 'key_2', 'key_3', 'key_4', 'key_5',
       'key_6', 'key_7', 'key_8', 'key_9', 'key_10', 'key_11', 'minor',
       'major', 'acousticness_ar', 'danceability_ar', 'duration_ms_ar',
       'energy_ar', 'instrumentalness_ar', 'liveness_ar', 'loudness_ar',
       'speechiness_ar', 'tempo_ar', 'valence_ar', 'popularity_ar', 'count',
       'genres', 'key_0_ar', 'key_1_ar', 'key_2_ar', 'key_3_ar', 'key_4_ar',
       'key_5_ar', 'key_6_ar', 'key_7_ar', 'key_8_ar', 'key_9_ar', 'key_10_ar',
       'key_11_ar', 'minor_ar', 'major_ar', 'acousticness_gr',
       'danceability_gr', 'duration_ms_gr', 'energy_gr', 'instrumentalness_gr',
       'liveness_gr', 'loudness_gr', 'speechiness_gr', 'tempo_gr',
       'valence_gr', 'popularity_gr', 'mode', 'key_0_gr', 'key_1_gr',
       'key_2_gr', 'key_3_gr', 'key_4_gr', 'key_5_gr', 'key_6_gr', 'key_7_gr',
       'key_8_gr', 'key_9_gr', 'key_10_gr', 'key_11_gr'],
      dtype='object')

In [85]:
df.tail()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,...,key_2_gr,key_3_gr,key_4_gr,key_5_gr,key_6_gr,key_7_gr,key_8_gr,key_9_gr,key_10_gr,key_11_gr
169903,42tFTth2jcF7iSo0RBjfJF,피카부 Peek-A-Boo,Red Velvet,189050,11/17/17,2017,0.0868,0.839,0.902,0.002570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169904,6XP9L7di5JnOc9WaeAW8oe,행복 (Happiness),Red Velvet,220987,8/1/14,2014,0.3230,0.727,0.871,0.000006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169905,3Gpdzw72aBVJSrm5J1leVK,"헤어지지 못하는 여자, 떠나가지 못하는 남자 Can't Breakup Girl, C...",Leessang,284627,10/6/09,2009,0.1500,0.523,0.841,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169905,3Gpdzw72aBVJSrm5J1leVK,"헤어지지 못하는 여자, 떠나가지 못하는 남자 Can't Breakup Girl, C...",Jung In,284627,10/6/09,2009,0.1500,0.523,0.841,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169906,2p5DfmIUTLH79elmaSCCR5,화려하지 않은 고백 Confession Is Not Flashy,LEE SEUNG HWAN,230733,9/1/93,1993,0.4480,0.741,0.380,0.000811,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
id_group = df.groupby('id')

In [87]:
df_group = id_group.agg({
    # Track Attributes
    "acousticness" : ["first"],
    "danceability" : ["first"],
    "duration_ms" : ["first"],
    "energy" : ["first"],
    "explicit" : ["first"],
    "instrumentalness" : ["first"],
    "liveness" : ["first"],
    "loudness" : ["first"],
    "popularity" : ["first"],
    "speechiness" : ["first"],
    "tempo" : ["first"],
    "valence" : ["first"],
    "year" : ["first"],
    "key_0" : ["first"],
    "key_1" : ["first"],
    "key_2" : ["first"],
    "key_3" : ["first"],
    "key_4" : ["first"],
    "key_5" : ["first"],
    "key_6" : ["first"],
    "key_7" : ["first"],
    "key_8" : ["first"],
    "key_9" : ["first"],
    "key_10" : ["first"],
    "key_11" : ["first"],
    "minor" : ["first"],
    "major" : ["first"],
    # Artist Attributes
    "acousticness_ar" : ["mean"],
    "danceability_ar" : ["mean"],
    "duration_ms_ar" : ["mean"],
    "energy_ar" : ["max"],
    "instrumentalness_ar" : ["max"],
    "liveness_ar" : ["max"],
    "loudness_ar" : ["mean"],
    "speechiness_ar" : ["mean"],
    "tempo_ar" : ["mean"],
    "valence_ar" : ["mean"],
    "popularity_ar" : ["max"],
    "count" : ["max"], # Doubtful, needs to be checked
    "key_0_ar" : ["first"],
    "key_1_ar" : ["first"],
    "key_2_ar" : ["first"],
    "key_3_ar" : ["first"],
    "key_4_ar" : ["first"],
    "key_5_ar" : ["first"],
    "key_6_ar" : ["first"],
    "key_7_ar" : ["first"],
    "key_8_ar" : ["first"],
    "key_9_ar" : ["first"],
    "key_10_ar" : ["first"],
    "key_11_ar" : ["first"],
    "minor_ar" : ["max"],
    "major_ar" : ["max"],
})

In [88]:
type(id_group)

pandas.core.groupby.generic.DataFrameGroupBy

In [89]:
df.columns

Index(['id', 'name', 'artists', 'duration_ms', 'release_date', 'year',
       'acousticness', 'danceability', 'energy', 'instrumentalness',
       'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity',
       'explicit', 'key_0', 'key_1', 'key_2', 'key_3', 'key_4', 'key_5',
       'key_6', 'key_7', 'key_8', 'key_9', 'key_10', 'key_11', 'minor',
       'major', 'acousticness_ar', 'danceability_ar', 'duration_ms_ar',
       'energy_ar', 'instrumentalness_ar', 'liveness_ar', 'loudness_ar',
       'speechiness_ar', 'tempo_ar', 'valence_ar', 'popularity_ar', 'count',
       'genres', 'key_0_ar', 'key_1_ar', 'key_2_ar', 'key_3_ar', 'key_4_ar',
       'key_5_ar', 'key_6_ar', 'key_7_ar', 'key_8_ar', 'key_9_ar', 'key_10_ar',
       'key_11_ar', 'minor_ar', 'major_ar', 'acousticness_gr',
       'danceability_gr', 'duration_ms_gr', 'energy_gr', 'instrumentalness_gr',
       'liveness_gr', 'loudness_gr', 'speechiness_gr', 'tempo_gr',
       'valence_gr', 'popularity_gr', 'mode', 'key_0_gr', 'key_1_gr',
       'key_2_gr', 'key_3_gr', 'key_4_gr', 'key_5_gr', 'key_6_gr', 'key_7_gr',
       'key_8_gr', 'key_9_gr', 'key_10_gr', 'key_11_gr'],
      dtype='object')

In [90]:
df.tail(15)

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,...,key_2_gr,key_3_gr,key_4_gr,key_5_gr,key_6_gr,key_7_gr,key_8_gr,key_9_gr,key_10_gr,key_11_gr
169893,6DVq2uRrYyQfChAlsTJ11g,비처럼 음악처럼,Kim Hyunshik,277580,12/1/86,1986,0.0496,0.430,0.338,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169894,7nKQ5WAcjnG48knyLuo8gO,빨간 맛 Red Flavor,Red Velvet,191139,7/9/17,2017,0.0409,0.709,0.917,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169895,1XwAV7ty94aIJgRXP7CETn,사랑이 지나가면,Lee Moon Sae,253240,3/10/87,1987,0.7670,0.308,0.286,0.000746,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169896,5hHlmrSV6d9LFMsDA1lamE,소방차 Fire Truck,NCT 127,178565,7/10/16,2016,0.1160,0.724,0.976,0.000013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169897,5w18nowVMRZrC5Na9Vxoth,"쏘리 쏘리 Sorry, Sorry",SUPER JUNIOR,232333,3/11/09,2009,0.0226,0.706,0.972,0.000003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169898,1uRB9bYGCSvLSsF4e65UYj,아로하,Cool,265379,4/19/04,2004,0.5160,0.529,0.754,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169899,4pi0Elz7B7cLfw37J3bYm9,으르렁 Growl,EXO,207053,8/5/13,2013,0.1450,0.681,0.814,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169900,2ujA6F1cpk3m8lsPE5aKua,전야 前夜 The Eve,EXO,176026,7/18/17,2017,0.0223,0.636,0.702,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169901,5NSPsOGVNWYOMeeyZPF7HY,중독 Overdose,EXO-K,205612,8/6/14,2014,0.0615,0.498,0.917,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169902,4KiYPYpm4ultIp247ftPlI,텅 빈 마음 Empty Heart,LEE SEUNG HWAN,249893,10/15/89,1989,0.4290,0.547,0.304,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169903,42tFTth2jcF7iSo0RBjfJF,피카부 Peek-A-Boo,Red Velvet,189050,11/17/17,2017,0.0868,0.839,0.902,0.002570,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169904,6XP9L7di5JnOc9WaeAW8oe,행복 (Happiness),Red Velvet,220987,8/1/14,2014,0.3230,0.727,0.871,0.000006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169905,3Gpdzw72aBVJSrm5J1leVK,"헤어지지 못하는 여자, 떠나가지 못하는 남자 Can't Breakup Girl, C...",Leessang,284627,10/6/09,2009,0.1500,0.523,0.841,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169905,3Gpdzw72aBVJSrm5J1leVK,"헤어지지 못하는 여자, 떠나가지 못하는 남자 Can't Breakup Girl, C...",Jung In,284627,10/6/09,2009,0.1500,0.523,0.841,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169906,2p5DfmIUTLH79elmaSCCR5,화려하지 않은 고백 Confession Is Not Flashy,LEE SEUNG HWAN,230733,9/1/93,1993,0.4480,0.741,0.380,0.000811,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
df = df.join(df_artist, on='artists', rsuffix='_ar')

In [92]:
df['artists'] = df['artists'].map(lambda x : x[0])

In [93]:
df.iloc[:,19]
count_nan = len(df.iloc[:,19]) - df.iloc[:,19].count()
print(len(df), count_nan)

225454 0

In [94]:
df.dropna(inplace=True)

In [95]:
df.iloc[:,19]

8         0
9         0
9         0
10        0
10        0
         ..
169790    0
169802    0
169803    0
169806    0
169815    1
Name: key_2, Length: 28591, dtype: int8

In [96]:
count_nan = len(df.iloc[:,19]) - df.iloc[:,19].count()
print(count_nan)

0

In [97]:
df_year.head()

,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key,mode
0,1920,0.631242,0.515750,238092.997135,0.418700,0.354219,0.216049,-12.654020,0.082984,113.226900,0.498210,0.610315,2,1
1,1921,0.862105,0.432171,257891.762821,0.241136,0.337158,0.205219,-16.811660,0.078952,102.425397,0.378276,0.391026,2,1
2,1922,0.828934,0.575620,140135.140496,0.226173,0.254776,0.256662,-20.840083,0.464368,100.033149,0.571190,0.090909,5,1
3,1923,0.957247,0.577341,177942.362162,0.262406,0.371733,0.227462,-14.129211,0.093949,114.010730,0.625492,5.205405,0,1
4,1924,0.940200,0.549894,191046.707627,0.344347,0.581701,0.235219,-14.231343,0.092089,120.689572,0.663725,0.661017,10,1

In [98]:
df_year[['key']].describe()

              key
count  102.000000
mean     3.794118
std      3.518940
min      0.000000
25%      0.000000
50%      2.000000
75%      7.000000
max     10.000000

In [99]:
df_year_key = df_year[['key']]
df_year_key_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_year_key).toarray()

In [100]:
df_year_key_onehot[:5]

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [101]:
df_year.drop(['key'], axis=1, inplace=True)

In [102]:
df_year = df_year.join(pd.DataFrame(df_year_key_onehot, columns=key_indices[:len(df_year_key_onehot[0])]))

In [103]:
df_year_mode = df_year[['mode']]
df_year_mode_onehot = OneHotEncoder(dtype=np.int8).fit_transform(df_year_mode).toarray()

In [104]:
df_year_mode_onehot[0]

array([1], dtype=int8)

In [105]:
df_year.head()

,year,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,mode,key_0,key_1,key_2,key_3,key_4,key_5,key_6
0,1920,0.631242,0.515750,238092.997135,0.418700,0.354219,0.216049,-12.654020,0.082984,113.226900,0.498210,0.610315,1,0,0,1,0,0,0,0
1,1921,0.862105,0.432171,257891.762821,0.241136,0.337158,0.205219,-16.811660,0.078952,102.425397,0.378276,0.391026,1,0,0,1,0,0,0,0
2,1922,0.828934,0.575620,140135.140496,0.226173,0.254776,0.256662,-20.840083,0.464368,100.033149,0.571190,0.090909,1,0,0,0,1,0,0,0
3,1923,0.957247,0.577341,177942.362162,0.262406,0.371733,0.227462,-14.129211,0.093949,114.010730,0.625492,5.205405,1,1,0,0,0,0,0,0
4,1924,0.940200,0.549894,191046.707627,0.344347,0.581701,0.235219,-14.231343,0.092089,120.689572,0.663725,0.661017,1,0,0,0,0,0,0,1

In [106]:

df = df_group.copy()
df.columns = df_group.columns.droplevel(1)

In [107]:
df.columns

Index(['acousticness', 'danceability', 'duration_ms', 'energy', 'explicit',
       'instrumentalness', 'liveness', 'loudness', 'popularity', 'speechiness',
       'tempo', 'valence', 'year', 'key_0', 'key_1', 'key_2', 'key_3', 'key_4',
       'key_5', 'key_6', 'key_7', 'key_8', 'key_9', 'key_10', 'key_11',
       'minor', 'major', 'acousticness_ar', 'danceability_ar',
       'duration_ms_ar', 'energy_ar', 'instrumentalness_ar', 'liveness_ar',
       'loudness_ar', 'speechiness_ar', 'tempo_ar', 'valence_ar',
       'popularity_ar', 'count', 'key_0_ar', 'key_1_ar', 'key_2_ar',
       'key_3_ar', 'key_4_ar', 'key_5_ar', 'key_6_ar', 'key_7_ar', 'key_8_ar',
       'key_9_ar', 'key_10_ar', 'key_11_ar', 'minor_ar', 'major_ar'],
      dtype='object')

In [108]:
df = df.join(df_year.set_index('year'), rsuffix='_yr', on='year')

In [109]:
df.dropna(inplace=True)

In [111]:
df.columns

Index(['acousticness', 'danceability', 'duration_ms', 'energy', 'explicit',
       'instrumentalness', 'liveness', 'loudness', 'popularity', 'speechiness',
       'tempo', 'valence', 'year', 'key_0', 'key_1', 'key_2', 'key_3', 'key_4',
       'key_5', 'key_6', 'key_7', 'key_8', 'key_9', 'key_10', 'key_11',
       'minor', 'major', 'acousticness_ar', 'danceability_ar',
       'duration_ms_ar', 'energy_ar', 'instrumentalness_ar', 'liveness_ar',
       'loudness_ar', 'speechiness_ar', 'tempo_ar', 'valence_ar',
       'popularity_ar', 'count', 'key_0_ar', 'key_1_ar', 'key_2_ar',
       'key_3_ar', 'key_4_ar', 'key_5_ar', 'key_6_ar', 'key_7_ar', 'key_8_ar',
       'key_9_ar', 'key_10_ar', 'key_11_ar', 'minor_ar', 'major_ar',
       'acousticness_yr', 'danceability_yr', 'duration_ms_yr', 'energy_yr',
       'instrumentalness_yr', 'liveness_yr', 'loudness_yr', 'speechiness_yr',
       'tempo_yr', 'valence_yr', 'popularity_yr', 'mode', 'key_0_yr',
       'key_1_yr', 'key_2_yr', 'key_3_yr', 'key_4_yr', 'key_5_yr', 'key_6_yr'],
      dtype='object')

In [112]:
dfml = df.copy()

In [113]:
from sklearn.tree import DecisionTreeRegressor
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import export_graphviz
from sklearn import tree
from sklearn.metrics import accuracy_score, r2_score

In [114]:

mean_popularity = 50
df["popularity"] = [ 1 if i >= mean_popularity else 0 for i in df.popularity ]

In [115]:
X  = dfml.drop(['popularity'], axis=1)
y = dfml['popularity']

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [117]:
tree_reg = DecisionTreeRegressor()
tree_reg.fit(X_train, y_train)

DecisionTreeRegressor()

In [118]:
y_pred_train = tree_reg.predict(X_train)

In [119]:
r2_score(y_train, y_pred_train)

0.997672042866691

In [120]:
y_pred = tree_reg.predict(X_test)

In [121]:
r2_score(y_test, y_pred)

0.7382507624565324

In [122]:
# criterion = ['gini', 'entropy']
max_depth = [10,15]
min_samples_split = [6,8]
min_samples_leaf = [5,6,7,8]

In [123]:
parameters=dict(max_depth=max_depth,
               min_samples_split=min_samples_split,
               min_samples_leaf=min_samples_leaf)

In [124]:
tree_reg_gs = GridSearchCV(tree_reg, parameters)
tree_reg_gs.fit(X_train,y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [10, 15],
                         'min_samples_leaf': [5, 6, 7, 8],
                         'min_samples_split': [6, 8]})

In [125]:
print('Best max_depth:', tree_reg_gs.best_estimator_.get_params()['max_depth'])
print('Best min_samples_split:', tree_reg_gs.best_estimator_.get_params()['min_samples_split'])
print('Best min_samples_leaf:', tree_reg_gs.best_estimator_.get_params()['min_samples_leaf'])

Best max_depth: 10
Best min_samples_split: 8
Best min_samples_leaf: 7

In [126]:
y_pred_train = tree_reg_gs.predict(X_train)
r2_score(y_train, y_pred_train)

0.8640148520167059

In [127]:
y_pred = tree_reg_gs.predict(X_test)
r2_score(y_test, y_pred)

0.8524298578335997